# Generated by Django 4.2.5 on 2023-09-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usertable',
        ),
        migrations.AddField(
            model_name='userdata',
            name='balance',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
